# -*- coding: utf-8 -*-
"""The colour behind a profile's initials, derived the way tofa derives it.

A profile with no picture gets a coloured disc, and the colour is not stored
anywhere: every tofa client computes it from the profile's **id**. Same id,
same colour, on every device the household owns -- which is the whole point.
It is an identity, not decoration, and it only works if we compute it the same
way they do.

**The `avatar_color` field on the profile is NOT this** and is not used by
anything: every profile on a real server carries the same value while the
apps draw different colours. Do not be tempted by it.

Measured 2026-09-18 from tofa's own web client, then verified against their
iPhone app (a photographed disc fitted to `#B68BFF -> #7B51D6` against this
table's entry 2, worst channel 3/255) and against the Apple TV app, where
three profiles wear the three colours this table predicts from their ids.

The hash is djb2 over UTF-16 code units. Their code writes the step with a
signed 32-bit shift, which is provably the same as `* 33` under the modulus
(checked over 20k uuids), so the plain form below is exact rather than
approximate.
"""
from __future__ import annotations

#: The eight gradients, IN ORDER. The order is the contract -- the index comes
#: from a hash, so reordering these repaints every profile in the household.
#: Each entry is (from, to), drawn top-left to bottom-right at 135 degrees.
PALETTE: tuple[tuple[str, str], ...] = (
    ("#3FD0C9", "#1E9FB8"),   # 0 teal
    ("#5C6BF2", "#2A2F66"),   # 1 indigo
    ("#B98CFF", "#7A4FD6"),   # 2 purple
    ("#FFB24C", "#FF6B3D"),   # 3 amber
    ("#FF7A8A", "#E03E63"),   # 4 rose
    ("#54D98B", "#1F9E6A"),   # 5 green
    ("#48D6F0", "#1F86C8"),   # 6 cyan
    ("#7C83FF", "#4A53D6"),   # 7 periwinkle
)

#: What an empty seed hashes instead. Theirs, verbatim.
FALLBACK_SEED = "tofa"

_MASK = 0xFFFFFFFF


def _hash(seed: str) -> int:
    """djb2 over UTF-16 code units, 32-bit.

    Kodi's Python is wide-build, so a character outside the BMP is ONE
    `ord()` where JavaScript sees two surrogates. Encoding to UTF-16 first is
    what keeps an emoji in a profile name hashing to their answer rather than
    to ours.
    """
    units = seed.encode("utf-16-le", "surrogatepass")
    value = 5381
    for i in range(0, len(units), 2):
        code = units[i] | (units[i + 1] << 8)
        value = (value * 33 + code) & _MASK
    return value


def index_for(seed: str) -> int:
    """Which PALETTE entry this seed lands on."""
    return _hash(seed or FALLBACK_SEED) % len(PALETTE)


def texture_for(seed: str) -> str:
    """The skin texture drawing that entry's gradient, masked to a disc.

    Generated by tools/gen_monogram_assets.py; the names are pinned by
    tests/test_monogram.py so a renamed file cannot go unnoticed.
    """
    return "monogram-%d.png" % index_for(seed)
