# -*- coding: utf-8 -*-
"""Advance widths for the fonts Python has to measure text in.

Kodi cannot size a control from a label's text length, and does not
expose font metrics either -- hence these tables. Summing per-character
advances ignores kerning, which measured within ~2px on real strings.

GENERATED by tools/gen_text_metrics.py -- do not hand-edit. Each table
belongs to ONE font at ONE size; using it for another font reads low (see
the note on text_width below).
"""
from __future__ import annotations

# tofa_font_metadata: inter_tight_regular.ttf @ 23
_ADVANCE_FONT = "tofa_font_metadata"
_ADVANCE_SIZE = 23
_ADVANCE_FALLBACK = 11.99
_ADVANCE = {
    ' ': 5.39,
    '!': 5.75,
    '"': 9.55,
    '#': 13.43,
    '$': 13.59,
    '%': 17.61,
    '&': 13.63,
    "'": 5.73,
    '(': 7.21,
    ')': 7.21,
    '*': 10.42,
    '+': 14.08,
    ',': 5.77,
    '-': 9.48,
    '.': 5.46,
    '/': 7.12,
    '0': 13.3,
    '1': 8.18,
    '2': 12.85,
    '3': 13.57,
    '4': 13.68,
    '5': 12.78,
    '6': 13.07,
    '7': 11.86,
    '8': 13.03,
    '9': 13.07,
    ':': 5.46,
    ';': 5.77,
    '<': 14.08,
    '=': 14.08,
    '>': 14.08,
    '?': 10.58,
    '@': 20.46,
    'A': 14.46,
    'B': 13.88,
    'C': 15.66,
    'D': 15.45,
    'E': 12.67,
    'F': 12.42,
    'G': 16.01,
    'H': 15.92,
    'I': 4.99,
    'J': 11.39,
    'K': 13.93,
    'L': 11.86,
    'M': 19.46,
    'N': 16.26,
    'O': 16.44,
    'P': 13.52,
    'Q': 16.44,
    'R': 13.63,
    'S': 13.59,
    'T': 13.68,
    'U': 15.97,
    'V': 14.46,
    'W': 20.91,
    'X': 13.68,
    'Y': 14.22,
    'Z': 13.3,
    '[': 7.21,
    '\\': 7.12,
    ']': 7.21,
    '^': 9.7,
    '_': 9.32,
    '`': 8.92,
    'a': 11.9,
    'b': 12.92,
    'c': 11.84,
    'd': 12.92,
    'e': 12.26,
    'f': 7.21,
    'g': 12.94,
    'h': 12.53,
    'i': 4.38,
    'j': 4.38,
    'k': 11.43,
    'l': 4.38,
    'm': 18.93,
    'n': 12.4,
    'o': 12.65,
    'p': 12.92,
    'q': 12.92,
    'r': 7.48,
    's': 10.94,
    't': 7.28,
    'u': 12.29,
    'v': 11.72,
    'w': 17.61,
    'x': 11.34,
    'y': 11.72,
    'z': 11.37,
    '{': 8.6,
    '|': 6.45,
    '}': 8.6,
    '~': 14.08,
    '\xa0': 5.39,
    '¡': 5.75,
    '¢': 11.84,
    '£': 13.43,
    '¤': 15.54,
    '¥': 11.52,
    '¦': 5.03,
    '§': 11.59,
    '¨': 12.51,
    '©': 19.97,
    'ª': 9.25,
    '«': 11.98,
    '¬': 11.34,
    '\xad': 9.48,
    '®': 14.35,
    '¯': 9.25,
    '°': 9.37,
    '±': 14.08,
    '²': 8.6,
    '³': 8.83,
    '´': 8.92,
    'µ': 13.23,
    '¶': 12.71,
    '·': 5.46,
    '¸': 5.05,
    '¹': 6.13,
    'º': 9.25,
    '»': 11.99,
    '¼': 19.2,
    '½': 20.19,
    '¾': 20.71,
    '¿': 10.58,
    'À': 14.46,
    'Á': 14.46,
    'Â': 14.46,
    'Ã': 14.46,
    'Ä': 14.46,
    'Å': 14.46,
    'Æ': 21.7,
    'Ç': 15.66,
    'È': 12.67,
    'É': 12.67,
    'Ê': 12.67,
    'Ë': 12.67,
    'Ì': 4.99,
    'Í': 4.99,
    'Î': 4.99,
    'Ï': 4.99,
    'Ð': 15.45,
    'Ñ': 16.26,
    'Ò': 16.44,
    'Ó': 16.44,
    'Ô': 16.44,
    'Õ': 16.44,
    'Ö': 16.44,
    '×': 14.08,
    'Ø': 16.44,
    'Ù': 15.97,
    'Ú': 15.97,
    'Û': 15.97,
    'Ü': 15.97,
    'Ý': 14.22,
    'Þ': 13.43,
    'ß': 12.94,
    'à': 11.9,
    'á': 11.9,
    'â': 11.9,
    'ã': 11.9,
    'ä': 11.9,
    'å': 11.9,
    'æ': 20.15,
    'ç': 11.84,
    'è': 12.26,
    'é': 12.26,
    'ê': 12.26,
    'ë': 12.26,
    'ì': 4.38,
    'í': 4.38,
    'î': 4.38,
    'ï': 4.38,
    'ð': 12.24,
    'ñ': 12.4,
    'ò': 12.65,
    'ó': 12.65,
    'ô': 12.65,
    'õ': 12.65,
    'ö': 12.65,
    '÷': 14.08,
    'ø': 12.65,
    'ù': 12.29,
    'ú': 12.29,
    'û': 12.29,
    'ü': 12.29,
    'ý': 11.72,
    'þ': 12.92,
    'ÿ': 11.72,
}

# tofa_font_hero_title: inter_tight_bold.ttf @ 61
_ADVANCE_HERO_TITLE_FONT = "tofa_font_hero_title"
_ADVANCE_HERO_TITLE_SIZE = 61
_ADVANCE_HERO_TITLE_FALLBACK = 34.42
_ADVANCE_HERO_TITLE = {
    ' ': 12.15,
    '!': 19.12,
    '"': 32.14,
    '#': 37.62,
    '$': 37.95,
    '%': 50.43,
    '&': 39.05,
    "'": 18.82,
    '(': 20.97,
    ')': 20.97,
    '*': 32.47,
    '+': 39.47,
    ',': 19.54,
    '-': 26.57,
    '.': 18.59,
    '/': 21.77,
    '0': 39.97,
    '1': 24.36,
    '2': 36.43,
    '3': 38.24,
    '4': 39.35,
    '5': 37.44,
    '6': 38.42,
    '7': 33.63,
    '8': 38.51,
    '9': 38.42,
    ':': 18.59,
    ';': 19.09,
    '<': 39.47,
    '=': 39.47,
    '>': 39.47,
    '?': 32.35,
    '@': 60.88,
    'A': 43.58,
    'B': 38.3,
    'C': 43.87,
    'D': 42.35,
    'E': 35.36,
    'F': 33.69,
    'G': 44.41,
    'H': 43.49,
    'I': 15.07,
    'J': 32.73,
    'K': 40.09,
    'L': 32.64,
    'M': 53.88,
    'N': 42.83,
    'O': 45.69,
    'P': 37.5,
    'Q': 45.75,
    'R': 38.07,
    'S': 37.95,
    'T': 38.78,
    'U': 42.5,
    'V': 43.58,
    'W': 61.21,
    'X': 41.58,
    'Y': 42.21,
    'Z': 38.66,
    '[': 20.97,
    '\\': 21.77,
    ']': 20.97,
    '^': 27.73,
    '_': 27.07,
    '`': 26.36,
    'a': 33.6,
    'b': 36.46,
    'c': 33.84,
    'd': 36.46,
    'e': 34.34,
    'f': 21.65,
    'g': 36.58,
    'h': 36.22,
    'i': 14.62,
    'j': 14.62,
    'k': 33.48,
    'l': 14.62,
    'm': 53.76,
    'n': 36.07,
    'o': 35.44,
    'p': 36.46,
    'q': 36.46,
    'r': 22.93,
    's': 32.26,
    't': 21.68,
    'u': 35.95,
    'v': 33.75,
    'w': 49.86,
    'x': 33.0,
    'y': 33.75,
    'z': 32.88,
    '{': 26.78,
    '|': 20.82,
    '}': 26.78,
    '~': 39.47,
    '\xa0': 12.15,
    '¡': 18.76,
    '¢': 33.84,
    '£': 38.99,
    '¤': 44.65,
    '¥': 32.88,
    '¦': 19.03,
    '§': 34.16,
    '¨': 30.62,
    '©': 53.82,
    'ª': 27.73,
    '«': 36.96,
    '¬': 33.36,
    '\xad': 26.57,
    '®': 38.48,
    '¯': 32.44,
    '°': 26.03,
    '±': 39.47,
    '²': 23.86,
    '³': 24.99,
    '´': 26.36,
    'µ': 38.66,
    '¶': 35.18,
    '·': 18.59,
    '¸': 20.85,
    '¹': 17.57,
    'º': 27.58,
    '»': 37.02,
    '¼': 51.53,
    '½': 53.76,
    '¾': 56.77,
    '¿': 32.32,
    'À': 43.58,
    'Á': 43.58,
    'Â': 43.58,
    'Ã': 43.58,
    'Ä': 43.58,
    'Å': 43.58,
    'Æ': 60.82,
    'Ç': 43.87,
    'È': 35.36,
    'É': 35.36,
    'Ê': 35.36,
    'Ë': 35.36,
    'Ì': 15.07,
    'Í': 15.07,
    'Î': 15.07,
    'Ï': 15.07,
    'Ð': 42.35,
    'Ñ': 42.83,
    'Ò': 45.69,
    'Ó': 45.69,
    'Ô': 45.69,
    'Õ': 45.69,
    'Ö': 45.69,
    '×': 39.47,
    'Ø': 45.69,
    'Ù': 42.5,
    'Ú': 42.5,
    'Û': 42.5,
    'Ü': 42.5,
    'Ý': 42.21,
    'Þ': 38.9,
    'ß': 38.21,
    'à': 33.6,
    'á': 33.6,
    'â': 33.6,
    'ã': 33.6,
    'ä': 33.6,
    'å': 33.6,
    'æ': 53.61,
    'ç': 33.84,
    'è': 34.34,
    'é': 34.34,
    'ê': 34.34,
    'ë': 34.34,
    'ì': 14.62,
    'í': 14.62,
    'î': 14.62,
    'ï': 14.62,
    'ð': 34.58,
    'ñ': 36.07,
    'ò': 35.44,
    'ó': 35.44,
    'ô': 35.44,
    'õ': 35.44,
    'ö': 35.44,
    '÷': 39.47,
    'ø': 35.44,
    'ù': 35.95,
    'ú': 35.95,
    'û': 35.95,
    'ü': 35.95,
    'ý': 33.75,
    'þ': 36.46,
    'ÿ': 33.75,
}

# Back-compat aliases: the metadata table predates the second one and is
# referenced as textmetrics.FONT / .SIZE / .text_width by detail.py,
# player.py, serverpicker.py and fragments.py.
FONT = _ADVANCE_FONT
SIZE = _ADVANCE_SIZE
_FALLBACK = _ADVANCE_FALLBACK


def text_width(text: str) -> int:
    """Rendered width of `text` in FONT, rounded up to whole pixels."""
    return int(round(sum(_ADVANCE.get(ch, _FALLBACK) for ch in text)))


def middle_ellipsis(text: str, max_px: int, font_size: int = SIZE) -> str:
    """`text` shortened from the MIDDLE until it fits `max_px`.

    Kodi ellipsises at the END, which is the wrong end for an address: it
    keeps the local part and throws away the domain, so every account on the
    same domain truncates to the same string. The app cuts the middle
    instead ("firstname.lastn...example.com"), keeping both ends, and this
    reproduces that.

    Measured, since the budgets are tight: a first.last address on a company
    domain runs to 320px, the identity card allows 310 and the sidebar row
    284, so BOTH truncate and the app's own rendering would not fit our
    sidebar.

    `font_size` converts the budget when the control uses the same FACE at
    another size, which several do: `tofa_font_body` is this same Inter
    Tight at 24 against this table's 23, so a string measured here renders
    ~4% wider and a budget taken at face value truncates twice -- measured,
    after Kodi added its own ellipsis on top of this one.
    """
    if font_size != SIZE:
        max_px = int(max_px * SIZE / float(font_size))
    if not text or text_width(text) <= max_px:
        return text
    ellipsis = "..."
    budget = max_px - text_width(ellipsis)
    if budget <= 0:
        return ellipsis
    # Grow head and tail alternately, head first, so the local part keeps
    # the extra character on an odd budget -- as the app's does.
    head, tail = "", ""
    for i in range(len(text)):
        want_head = (i % 2 == 0)
        nxt_head = text[:len(head) + 1] if want_head else head
        nxt_tail = tail if want_head else text[len(text) - len(tail) - 1:]
        if len(nxt_head) + len(nxt_tail) >= len(text):
            break
        if text_width(nxt_head + nxt_tail) > budget:
            break
        head, tail = nxt_head, nxt_tail
    return head + ellipsis + tail


def hero_title_width(text: str) -> float:
    """Width of `text` in tofa_font_hero_title (inter_tight_bold @ 61)."""
    return sum(
        _ADVANCE_HERO_TITLE.get(c, _ADVANCE_HERO_TITLE_FALLBACK) for c in text)


def hero_title_wrap(text: str, column_px: int) -> tuple[str, int]:
    """Break `text` for the hero title box; returns (label, line count).

    WHY THIS EXISTS. Kodi cannot bottom-align a label: the XML parser maps
    <aligny>bottom</aligny> to the SAME value as top (GUIControlFactory
    passes {0, 0, XBFONT_CENTER_Y, 0} as {default, top, center, bottom}),
    and CGUILabelControl never derives its height from its text -- it
    overrides GetWidth() for <width>auto</width> but has no GetHeight().
    So a one-line title and a two-line one occupy the same box and the text
    hangs from the TOP, leaving a gap under a short title. The skin fixes
    that by sliding the label down one line when there is only one, which
    means the count has to be known before the label is drawn.

    The break is inserted HERE, as Kodi's [CR], rather than left to
    <wrapmultiline>. Our advance sum ignores kerning and lands ~1px off
    Kodi's own measurement, which is invisible until a title falls within
    a pixel or two of the column -- then we would predict two lines and
    Kodi would draw one, sliding the title a whole line out of place.
    Emitting the break makes the two agree by construction.

    Greedy, like Kodi: break before the first word that would overflow.
    Capped at two lines, which is what the box holds; a longer title
    ellipsises on the second exactly as it always did."""
    if not text or hero_title_width(text) <= column_px:
        return text, 1
    line = ""
    for i, word in enumerate(text.split(" ")):
        candidate = word if not line else line + " " + word
        if line and hero_title_width(candidate) > column_px:
            rest = " ".join(text.split(" ")[i:])
            return line + "[CR]" + rest, 2
        line = candidate
    return text, 1
