# -*- coding: utf-8 -*-
"""Advance widths for tofa_font_metadata (inter_tight_regular @ 23), so
Python can size a control to its own text.

Kodi cannot size a control from a label's text length, which is why the
format badges used to be fixed-width slots. But `xbmcgui.Control.setWidth()`
exists, so a runtime measure-then-resize does work -- it just needs the font
metrics, which Kodi does not expose either. Hence this table.

Generated by tools/gen_text_metrics.py from the bundled TTF; regenerate if
that font or its size changes. Summing per-character advances ignores
kerning, which measured within ~2px on the real badge strings (checked
against PIL's own getlength for "4K"/"HDR10"/"DTS-HD MA 5.1"), and the
badges are padded by 13px a side so a couple of px never shows.
"""
from __future__ import annotations

FONT = "tofa_font_metadata"
SIZE = 23
_FALLBACK = 11.72

_ADVANCE = {
    ' ': 5.39,
    '!': 5.75,
    '"': 9.55,
    '#': 13.44,
    '$': 13.59,
    '%': 17.61,
    '&': 13.64,
    "'": 5.73,
    '(': 7.2,
    ')': 7.2,
    '*': 10.42,
    '+': 14.08,
    ',': 5.77,
    '-': 9.48,
    '.': 5.45,
    '/': 7.12,
    '0': 13.3,
    '1': 8.17,
    '2': 12.84,
    '3': 13.56,
    '4': 13.67,
    '5': 12.78,
    '6': 13.08,
    '7': 11.86,
    '8': 13.03,
    '9': 13.08,
    ':': 5.45,
    ';': 5.77,
    '<': 14.08,
    '=': 14.08,
    '>': 14.08,
    '?': 10.58,
    '@': 20.47,
    'A': 14.47,
    'B': 13.88,
    'C': 15.66,
    'D': 15.45,
    'E': 12.67,
    'F': 12.42,
    'G': 16.02,
    'H': 15.92,
    'I': 4.98,
    'J': 11.39,
    'K': 13.92,
    'L': 11.86,
    'M': 19.47,
    'N': 16.27,
    'O': 16.44,
    'P': 13.52,
    'Q': 16.44,
    'R': 13.64,
    'S': 13.59,
    'T': 13.67,
    'U': 15.97,
    'V': 14.47,
    'W': 20.91,
    'X': 13.67,
    'Y': 14.22,
    'Z': 13.3,
    '[': 7.2,
    '\\': 7.12,
    ']': 7.2,
    '^': 9.7,
    '_': 9.33,
    '`': 8.92,
    'a': 11.91,
    'b': 12.92,
    'c': 11.84,
    'd': 12.92,
    'e': 12.27,
    'f': 7.2,
    'g': 12.94,
    'h': 12.53,
    'i': 4.38,
    'j': 4.38,
    'k': 11.44,
    'l': 4.38,
    'm': 18.94,
    'n': 12.41,
    'o': 12.64,
    'p': 12.92,
    'q': 12.92,
    'r': 7.48,
    's': 10.94,
    't': 7.28,
    'u': 12.28,
    'v': 11.72,
    'w': 17.61,
    'x': 11.34,
    'y': 11.72,
    'z': 11.36,
    '{': 8.61,
    '|': 6.45,
    '}': 8.61,
    '~': 14.08,
}


def text_width(text: str) -> int:
    """Rendered width of `text` in FONT, rounded up to whole pixels."""
    return int(round(sum(_ADVANCE.get(ch, _FALLBACK) for ch in text)))


def middle_ellipsis(text: str, max_px: int, font_size: int = SIZE) -> str:
    """`text` shortened from the MIDDLE until it fits `max_px`.

    Kodi ellipsises at the END, which is the wrong end for an address: it
    keeps the local part and throws away the domain, so every account on the
    same domain truncates to the same string. The app cuts the middle
    instead ("firstname.lastn...example.com"), keeping both ends, and this
    reproduces that.

    Measured, since the budgets are tight: a first.last address on a company
    domain runs to 320px, the identity card allows 310 and the sidebar row
    284, so BOTH truncate and the app's own rendering would not fit our
    sidebar.

    `font_size` converts the budget when the control uses the same FACE at
    another size, which several do: `tofa_font_body` is this same Inter
    Tight at 24 against this table's 23, so a string measured here renders
    ~4% wider and a budget taken at face value truncates twice -- measured,
    after Kodi added its own ellipsis on top of this one.
    """
    if font_size != SIZE:
        max_px = int(max_px * SIZE / float(font_size))
    if not text or text_width(text) <= max_px:
        return text
    ellipsis = "..."
    budget = max_px - text_width(ellipsis)
    if budget <= 0:
        return ellipsis
    # Grow head and tail alternately, head first, so the local part keeps
    # the extra character on an odd budget -- as the app's does.
    head, tail = "", ""
    for i in range(len(text)):
        want_head = (i % 2 == 0)
        nxt_head = text[:len(head) + 1] if want_head else head
        nxt_tail = tail if want_head else text[len(text) - len(tail) - 1:]
        if len(nxt_head) + len(nxt_tail) >= len(text):
            break
        if text_width(nxt_head + nxt_tail) > budget:
            break
        head, tail = nxt_head, nxt_tail
    return head + ellipsis + tail
