# -*- coding: utf-8 -*-
"""Regenerate resources/lib/textmetrics.py from the bundled TTFs.

textmetrics.py's docstring has always named this file, but it was never
committed -- so the one table in there could not be re-derived, and adding a
second one meant hand-typing ~94 floats. Recovered 2026-08-19 by finding the
recipe that reproduces the existing table EXACTLY (all 94 advances, 0
mismatches): PIL rounds `getlength` to whole pixels at a UI size, so measure
at 100x the target and divide. That is why BIG_SCALE exists.

    python3 tools/gen_text_metrics.py            # rewrite the module
    python3 tools/gen_text_metrics.py --check    # verify it is current

Regenerate whenever a bundled .ttf changes or a table's size moves. --check
is what CI would run; it fails loudly rather than letting the table drift
away from the font the app actually renders.
"""
from __future__ import annotations

import argparse
import os
import sys

try:
    from PIL import ImageFont
except ImportError:                                     # pragma: no cover
    sys.exit("gen_text_metrics: needs Pillow (the system python3 has it)")

_TOOLS = os.path.dirname(os.path.abspath(__file__))
_ADDON = os.path.join(_TOOLS, "..", "plugin.video.tofa")
# The fonts moved out of the plugin into resource.font.tofa, which is the
# add-on Kodi resolves a font FILE against; they are prefixed there so the
# active skin's own fonts/ cannot shadow one. See fontinstall.py.
_FONTS = os.path.join(_TOOLS, "..", "resource.font.tofa", "resources")
_OUT = os.path.join(_ADDON, "resources", "lib", "textmetrics.py")

BIG_SCALE = 100

# The printable Latin-1 range the UI can put in a measured label. Kept to
# exactly what the existing table carried so a regeneration is a no-op.
_CHARS = [chr(c) for c in range(32, 127)] + [
    chr(c) for c in range(160, 256)
]

# (table name, font role it serves, .ttf, size)
_TABLES = [
    ("_ADVANCE", "tofa_font_metadata", "tofa_inter_tight_regular.ttf", 23),
    ("_ADVANCE_HERO_TITLE", "tofa_font_hero_title", "tofa_inter_tight_bold.ttf", 61),
]


def _advances(ttf: str, size: int) -> dict[str, float]:
    """Unhinted advance per character, in pixels at `size`.

    Measured at BIG_SCALE x and divided back: PIL quantises getlength() to
    whole pixels at UI sizes, which would throw away the fraction that makes
    a 40-character string land within a pixel of the real render."""
    font = ImageFont.truetype(os.path.join(_FONTS, ttf), size * BIG_SCALE)
    out = {}
    for ch in _CHARS:
        try:
            w = font.getlength(ch) / float(BIG_SCALE)
        except Exception:
            continue
        if w > 0:
            out[ch] = round(w, 2)
    return out


def _render() -> str:
    body = ['# -*- coding: utf-8 -*-',
            '"""Advance widths for the fonts Python has to measure text in.',
            '',
            'Kodi cannot size a control from a label\'s text length, and does not',
            'expose font metrics either -- hence these tables. Summing per-character',
            'advances ignores kerning, which measured within ~2px on real strings.',
            '',
            'GENERATED by tools/gen_text_metrics.py -- do not hand-edit. Each table',
            'belongs to ONE font at ONE size; using it for another font reads low (see',
            'the note on text_width below).',
            '"""',
            'from __future__ import annotations',
            '']
    for name, role, ttf, size in _TABLES:
        adv = _advances(ttf, size)
        fallback = round(sum(adv.values()) / len(adv), 2)
        body.append(f'# {role}: {ttf} @ {size}')
        body.append(f'{name}_FONT = "{role}"')
        body.append(f'{name}_SIZE = {size}')
        body.append(f'{name}_FALLBACK = {fallback}')
        body.append(f'{name} = {{')
        for ch in sorted(adv):
            body.append(f'    {ch!r}: {adv[ch]},')
        body.append('}')
        body.append('')

    # Everything from text_width down is the module's PRE-EXISTING public
    # API, carried through verbatim. It is not generated FROM anything --
    # it is preserved. A first cut of this generator rewrote the module
    # from scratch and silently dropped middle_ellipsis() (which draws the
    # Settings account line) and changed text_width() from int to float,
    # which broke Detail's badge packing: xbmcgui setWidth/setPosition
    # take ints, so the row threw TypeError and the whole hero render
    # aborted with it. Add to this list; do not reimplement it.
    body += [
        '# Back-compat aliases: the metadata table predates the second one and is',
        '# referenced as textmetrics.FONT / .SIZE / .text_width by detail.py,',
        '# player.py, serverpicker.py and fragments.py.',
        'FONT = _ADVANCE_FONT',
        'SIZE = _ADVANCE_SIZE',
        '_FALLBACK = _ADVANCE_FALLBACK',
        '',
        '',
        'def text_width(text: str) -> int:',
        '    """Rendered width of `text` in FONT, rounded up to whole pixels."""',
        '    return int(round(sum(_ADVANCE.get(ch, _FALLBACK) for ch in text)))',
        '',
        '',
        'def middle_ellipsis(text: str, max_px: int, font_size: int = SIZE) -> str:',
        '    """`text` shortened from the MIDDLE until it fits `max_px`.',
        '',
        '    Kodi ellipsises at the END, which is the wrong end for an address: it',
        '    keeps the local part and throws away the domain, so every account on the',
        '    same domain truncates to the same string. The app cuts the middle',
        '    instead ("firstname.lastn...example.com"), keeping both ends, and this',
        '    reproduces that.',
        '',
        '    Measured, since the budgets are tight: a first.last address on a company',
        '    domain runs to 320px, the identity card allows 310 and the sidebar row',
        "    284, so BOTH truncate and the app's own rendering would not fit our",
        '    sidebar.',
        '',
        '    `font_size` converts the budget when the control uses the same FACE at',
        '    another size, which several do: `tofa_font_body` is this same Inter',
        "    Tight at 24 against this table's 23, so a string measured here renders",
        '    ~4% wider and a budget taken at face value truncates twice -- measured,',
        '    after Kodi added its own ellipsis on top of this one.',
        '    """',
        '    if font_size != SIZE:',
        '        max_px = int(max_px * SIZE / float(font_size))',
        '    if not text or text_width(text) <= max_px:',
        '        return text',
        '    ellipsis = "..."',
        '    budget = max_px - text_width(ellipsis)',
        '    if budget <= 0:',
        '        return ellipsis',
        '    # Grow head and tail alternately, head first, so the local part keeps',
        "    # the extra character on an odd budget -- as the app's does.",
        '    head, tail = "", ""',
        '    for i in range(len(text)):',
        '        want_head = (i % 2 == 0)',
        '        nxt_head = text[:len(head) + 1] if want_head else head',
        '        nxt_tail = tail if want_head else text[len(text) - len(tail) - 1:]',
        '        if len(nxt_head) + len(nxt_tail) >= len(text):',
        '            break',
        '        if text_width(nxt_head + nxt_tail) > budget:',
        '            break',
        '        head, tail = nxt_head, nxt_tail',
        '    return head + ellipsis + tail',
        '',
        '',
        'def hero_title_width(text: str) -> float:',
        '    """Width of `text` in tofa_font_hero_title (inter_tight_bold @ 61)."""',
        '    return sum(',
        '        _ADVANCE_HERO_TITLE.get(c, _ADVANCE_HERO_TITLE_FALLBACK) for c in text)',
        '',
        '',
        'def hero_title_wrap(text: str, column_px: int) -> tuple[str, int]:',
        '    """Break `text` for the hero title box; returns (label, line count).',
        '',
        '    WHY THIS EXISTS. Kodi cannot bottom-align a label: the XML parser maps',
        '    <aligny>bottom</aligny> to the SAME value as top (GUIControlFactory',
        '    passes {0, 0, XBFONT_CENTER_Y, 0} as {default, top, center, bottom}),',
        '    and CGUILabelControl never derives its height from its text -- it',
        '    overrides GetWidth() for <width>auto</width> but has no GetHeight().',
        '    So a one-line title and a two-line one occupy the same box and the text',
        '    hangs from the TOP, leaving a gap under a short title. The skin fixes',
        '    that by sliding the label down one line when there is only one, which',
        '    means the count has to be known before the label is drawn.',
        '',
        '    The break is inserted HERE, as Kodi\'s [CR], rather than left to',
        '    <wrapmultiline>. Our advance sum ignores kerning and lands ~1px off',
        '    Kodi\'s own measurement, which is invisible until a title falls within',
        '    a pixel or two of the column -- then we would predict two lines and',
        '    Kodi would draw one, sliding the title a whole line out of place.',
        '    Emitting the break makes the two agree by construction.',
        '',
        '    Greedy, like Kodi: break before the first word that would overflow.',
        '    Capped at two lines, which is what the box holds; a longer title',
        '    ellipsises on the second exactly as it always did."""',
        '    if not text or hero_title_width(text) <= column_px:',
        '        return text, 1',
        '    line = ""',
        '    for i, word in enumerate(text.split(" ")):',
        '        candidate = word if not line else line + " " + word',
        '        if line and hero_title_width(candidate) > column_px:',
        '            rest = " ".join(text.split(" ")[i:])',
        '            return line + "[CR]" + rest, 2',
        '        line = candidate',
        '    return text, 1',
        '',
    ]
    return "\n".join(body)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed module is not what this "
                         "generator produces")
    args = ap.parse_args()
    new = _render()
    if args.check:
        with open(_OUT, encoding="utf-8") as f:
            if f.read() != new:
                sys.exit("gen_text_metrics: textmetrics.py is STALE -- "
                         "run python3 tools/gen_text_metrics.py")
        print("textmetrics.py is current")
        return
    with open(_OUT, "w", encoding="utf-8") as f:
        f.write(new)
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    main()
